name: Lint and Test

on:
  push:
    branches: [develop, master]
  pull_request:
    types: [opened, synchronize]  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install --frozen-lockfile --check-files
      - name: Save cache
        uses: actions/cache@v1
        id: cache-build
        with:
          path: '.'
          key: ${{ github.sha }}  

  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Restore cache
        uses: actions/cache@v1
        id: restore-build
        with:
          path: '.'
          key: ${{ github.sha }}
      - name: Lint code
        run: yarn lint

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Restore cache
        uses: actions/cache@v1
        id: restore-build
        with:
          path: '.'
          key: ${{ github.sha }}
      - name: Run tests
        run: yarn test:coverage
      - name: Publish coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Publish coverage to Code Climate
        uses: paambaati/codeclimate-action@v2.6.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE_TEST_REPORTER_ID }}